# Generated by Django 5.2.16 on 2026-07-20 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('fabric_blend', models.CharField(max_length=100)),
                ('fabric_quality', models.CharField(max_length=100)),
                ('warp', models.CharField(max_length=50)),
                ('warp_blend', models.CharField(blank=True, max_length=50, null=True)),
                ('weft', models.CharField(max_length=50)),
                ('weft_blend', models.CharField(blank=True, max_length=50, null=True)),
                ('ends', models.PositiveIntegerField()),
                ('picks', models.PositiveIntegerField()),
                ('weave', models.CharField(max_length=50)),
                ('greige_width_on_loom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('greige_width_off_loom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selvedge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(choices=[('MTR', 'Meter (MTR)'), ('YARD', 'Yard'), ('KG', 'Kilogram')], default='MTR', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'db_table': 'fabric',
                'ordering': ['-created_at'],
            },
        ),
    ]
