# Generated by Django 5.2.16 on 2026-07-20 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0004_fabric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tolerance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delivery_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.agent')),
                ('buying_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.buyinghouse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.manufacturer')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_order',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
    ]
