# Generated by Django 5.2.16 on 2026-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
