# Generated by Django 5.2.16 on 2026-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_phone_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_masters', 'Can view Masters module'), ('can_view_purchase', 'Can view Purchase module'), ('can_view_inventory', 'Can view Inventory module'), ('can_view_sales', 'Can view Sales module'), ('can_view_reports', 'Can view Reports module'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
