# Generated by Django 5.2.16 on 2026-07-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0004_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreigeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reserved_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greige_stock', to='masters.fabric')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.manufacturer')),
            ],
            options={
                'verbose_name': 'Greige Stock',
                'verbose_name_plural': 'Greige Stock',
                'db_table': 'greige_stock',
            },
        ),
    ]
