# Generated by Django 5.2.16 on 2026-07-21 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0004_fabric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('dispatch_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('shade', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finish', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.manufacturer')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'db_table': 'dispatch',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=100)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='inventory.dispatch')),
            ],
            options={
                'verbose_name': 'Dispatch Specification',
                'verbose_name_plural': 'Dispatch Specifications',
                'db_table': 'dispatch_specification',
            },
        ),
        migrations.CreateModel(
            name='TransitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_stock', to='masters.fabric')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.manufacturer')),
            ],
            options={
                'verbose_name': 'Transit Stock',
                'verbose_name_plural': 'Transit Stock',
                'db_table': 'transit_stock',
                'unique_together': {('fabric', 'manufacturer')},
            },
        ),
    ]
