# Generated by Django 5.2.16 on 2026-07-21 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dispatch_dispatchspecification_transitstock'),
        ('masters', '0004_fabric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('receiving_date', models.DateField(default=django.utils.timezone.now)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='inventory.dispatch')),
            ],
            options={
                'db_table': 'processing_receiving',
                'ordering': ['-receiving_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_a', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grade_b', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.manufacturer')),
            ],
            options={
                'db_table': 'finished_stock',
                'unique_together': {('fabric', 'manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingReceivingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('dispatch_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('grade_a', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grade_b', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('loss', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('gain', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('loss_percent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('gain_percent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='inventory.processingreceiving')),
            ],
            options={
                'db_table': 'processing_receiving_grade',
                'unique_together': {('receiving', 'color')},
            },
        ),
    ]
