# Generated by Django 5.2.16 on 2026-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_processingreceiving_finishedstock_and_more'),
        ('masters', '0004_fabric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'ordering': ['-dispatch_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='finishedstock',
            options={'verbose_name': 'Finished Stock', 'verbose_name_plural': 'Finished Stock'},
        ),
        migrations.AlterModelOptions(
            name='transitstock',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='finishedstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='finishedstock',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedstock',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='finishedstock',
            unique_together={('fabric', 'manufacturer', 'color')},
        ),
    ]
