# Generated by Django 5.2.16 on 2026-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10)),
                ('primary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('sidebar_style', models.CharField(default='default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appearance Setting',
                'verbose_name_plural': 'Appearance Settings',
                'db_table': 'settings_appearance',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Fabric Management System', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('ntn', models.CharField(blank=True, max_length=50, null=True, verbose_name='NTN / Tax Number')),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('default_unit', models.CharField(default='MTR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
                'db_table': 'settings_company_info',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('po_prefix', models.CharField(default='PO-', max_length=20)),
                ('dispatch_prefix', models.CharField(default='DSP-', max_length=20)),
                ('sales_prefix', models.CharField(default='SAL-', max_length=20)),
                ('invoice_footer', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Setting',
                'verbose_name_plural': 'Invoice Settings',
                'db_table': 'settings_invoice',
            },
        ),
    ]
